src/aimgroup/DashboardBundle/Form/FaqType.php
<?php

namespace aimgroup\DashboardBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\Exception\AccessException;
use Symfony\Component\OptionsResolver\OptionsResolver;
use aimgroup\DashboardBundle\Entity\Faq;

class FaqType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('faqName')
            ->add('faqContent')
        ;
    }

    /**
     * @param OptionsResolver $resolver
     *
     * @throws AccessException
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Faq::class
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'dashboardbundle_faq';
    }
}

src/aimgroup/DashboardBundle/Resources/views/Admin/blacklisted.html.twig
{% extends '::simreg.html.twig' %}

{% block body -%}
    <h1>Faq list</h1>

    <ul class="pull-right">
        <li>
            <a href="{{ path('faq_new') }}">
                Create a new entry
            </a>
        </li>
    </ul>

    <table class="table table-striped table-bordered table-hover dataTables-example dataTable dtr-inline" id="DataTables_Table_0">
        <thead>
            <tr>
                <th>Id</th>
                <th>Faqname</th>
                <th style="width:20%">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for entity in entities %}
                <tr>
                    <td><a href="{{ path('faq_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                    <td>{{ entity.name }}</td>
                    <td>
                        <ul>
                            <li>
                                <a href="{{ path('faq_show', { 'id': entity.id }) }}">show</a>
                            </li>
                            <li>
                                <a href="{{ path('faq_edit', { 'id': entity.id }) }}">edit</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


{% endblock %}

src/aimgroup/DashboardBundle/Resources/views/Admin/edit_role_department.html.twig
{% extends '::simreg.html.twig' %}

{% block body -%}
    <h1>{{ title }}</h1>

    <link rel="stylesheet" type="text/css" href="{{ asset('assets/easyui.css') }}">
    <script type="text/javascript" src="{{ asset('assets/jquery.easyui.min.js') }}"></script>



    <form role="form" method="POST" action="{{ path('admin') }}edit_role_department_action/{{ dept_id }}" _lpchecked="1" id="DeptRolePermsForm">

        <div class="easyui-panel" style="padding:5px">
            <ul id="tt" class="easyui-tree i-checks" data-options="url:'{{ asset('assets/tree_data.json') }}',method:'get',animate:true,checkbox:true"></ul>
        </div>


        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>
    </form>

    <script type="text/javascript">
        function getChecked() {
            var nodes = $('#tt').tree('getChecked');
            var s = '';
            for (var i = 0; i < nodes.length; i++) {
                if (s != '')
                    s += ',';
                s += nodes[i].text;
            }
            alert(s);
        }
    </script>


    <style>
        .easyui-tree>li>.tree-node>input[type=checkbox]{
            display: none;
        }
        .panel-header, .panel-body {
            border-color: #FFFFFF;
        }
    </style>

    <!-- iCheck -->

    <link href="{{ asset('assets/css/plugins/iCheck/custom.css') }}" rel="stylesheet">
    <script src="{{ asset('assets/js/plugins/iCheck/icheck.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });

        $(document).ready(function () {

        });


        function explode() {
            var saved_perms
            = {{ entity_perms }};
                    for (index = 0; index < saved_perms.length; index++) {
                $('input#perm_id_' + saved_perms[index]).prop('checked', true);
                //$('input#perm_id_' + saved_perms[index]).attr("checked", "checked");

            }
        }
        setTimeout(explode, 3000);

    </script>

{% endblock %}

src/aimgroup/DashboardBundle/Resources/views/Admin/ported_numbers.html.twig
{% extends '::simreg.html.twig' %}

{% block body -%}
    <h1>{{title_descr}}</h1>


    <div class="row">

        <div class="col-md-12">
            
            <div class="panel-group {{hide_search_class}}" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne"  data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        <h4 class="panel-title" style="text-align: center;font-size: 16px;font-weight: 300;color: #747779;">
                            <i class="fa fa-search"></i> Search Fields</h4>
                        <span style="width: 30px; float: right; margin-top: -20px;">
                            <i class="fa fa-arrow-down"></i>
                        </span>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">

                            <div class="col-md-2"></div>
                            <div class="col-md-8">

                                <form action="{{ path('admin') }}registrations_filter" method="post" name="dashboardbundle_admin">
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <label>Customer MSISDN:</label>
                                            <input name="customer_msisdn" id="customer_msisdn" type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>First Name:</label>
                                                <input name="first_name" id="first_name" type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Last Name:</label>
                                                <input name="last_name" id="last_name" type="text" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>ID Type:</label>
                                                <select name="id_type_name" id="id_type_name" class="form-control">
                                                    <option value="">Select ID Type</option>
                                                    {% for idd in idtype %}
                                                        <option value="{{ idd.id }}">{{ idd.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>ID Number:</label>
                                                <input name="id_number" id="id_number" type="text" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-4">
                                            <div class="form-group">
                                                <label>Registrar First Name:</label>
                                                <input name="agent_firstname" id="agent_firstname" type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group">
                                                <label>Registrar Last Name:</label>
                                                <input name="agent_lastname" id="agent_lastname" type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group">
                                                <label>Registrar Phone:</label>
                                                <input name="agent_phone" id="agent_phone" type="text" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <!--<div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Registration Type:</label>
                                                <select name="reg_type" class="form-control" id="resolution">
                                                    <option>New Registration</option>
                                                    <option>Re-Registration</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Registration State:</label>
                                                <select name="reg_state" class="form-control" id="resolution">
                                                    <option>Pending Received Information</option>
                                                    <option>Pending Registration Process</option>
                                                    <option>Temporary Activation</option>
                                                    <option>Full Activation</option>
                                                    <option>Declined</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>-->
                                    <div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Region:</label>
                                                <select class="form-control" id="search_region" name="region"
                                                        onchange="getTerritoriesCode();"></select>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Territory:</label>
                                                <select class="form-control  validate[required]" id="search_territory"
                                                        name="territory"></select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>From Date:</label>
                                                <input name="from_date" id="from_date" type="text" class="datepickers form-control">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>To Date:</label>
                                                <input name="to_date" id="to_date" type="text" class="datepickers form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>iCAP Status</label>
                                                <select name="icap_status" class=" form-control" id="icap_status">
                                                    <option value="">Select</option>
                                                    <option value="notsent">Not Sent</option>
                                                    <option value="declined">Declined</option>
                                                    <option value="freg">Freg</option>
                                                    <option value="treg">Treg</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>EReg Status</label>
                                                <select name="ereg_status" class=" form-control" id="ereg_status">
                                                    <option value="">Select</option>
                                                    <option value="pending">Pending</option>
                                                    <option value="submitted">Submitted</option>
                                                    <option value="declined">Declined</option>
                                                    <option value="received">Received</option>
                                                    <option value="audited">Audited</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="hr-line-dashed"></div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col-sm-8  col-sm-offset-4">
                                            <button id="LoadRecordsButtonBBreset" class="btn btn-default" type="submit">Reset Filters</button>

                                            <button id="LoadRecordsButtonBB" class="btn btn-primary" type="submit">Search Registrations</button>
                                        </div>
                                    </div>

                                </form>

                            </div>
                            <div class="col-md-2"></div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="PortInRequestTableContainer"></div>

    <br /><br />

    <script type="text/javascript" src="{{ asset('assets/jquery.restable.min.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('assets/jquery.restable.min.css') }}">
    <script src="{{ asset('assets/js/core/ported_registrations.js') }}"></script>
    <script src="{{ asset('assets/js/core/agents.js') }}"></script>
    <script>
        $(document).ready(function () {
            loadPortInRequestTables();
            getRegionsCode();

            $(".datepickers").datepicker({
                changeMonth: true,
                changeYear: true
            });
        });
    </script>

{% endblock %}

src/aimgroup/DashboardBundle/Resources/views/Admin/reports_verifyer.html.twig
{% extends '::simreg_actions.html.twig' %}

{% block body -%}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-4">
            <h2>{{title}}</h2>
        </div>

    </div>
    <div class="wrapper wrapper-content">
        <div class="row dynamic_form_container">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">

                    <div class="ibox-content">
                        <div class="col-lg-8">
                            
                            
                            
                            <h1 style="color:#FE910D; font-weight: 600;">{{ message }}</h1>
                            
                            
                            <form action="/admin/newreportspost" method="post" name="dashboardbundle_admin">
                                <div class="form-group">
                                    <label>Email Address:</label>
                                    <input name="emailAddress" type="text" class="form-control" id="emailAddress" required="required">
                                    <input name="verifyer" value="1" type="hidden" class="form-control" id="verifyer" required="required">
                                </div>
                                <div class="form-group">
                                    <label>Report For:</label>
                                    <select name="report_type" class="form-control">
                                        <option value="agent_registration">Agent Registration Report</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-6 no-padding">
                                        <div class="form-group">
                                            <label>From Date:</label>
                                            <input name="from_date" type="date" class="form-control" id="loginTrials">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>To Date:</label>
                                            <input name="to_date" type="date" class="form-control" id="loginTrials" >
                                            <input name="verify_info" type="hidden" value="1" class="form-control" id="verify_info" >
                                        </div>
                                    </div>
                                    <p class="help-block"><strong>Note:</strong> If date is not specified, report generates for the last 24 hours.</p>
                                </div>
                                
                                <!--<div class="form-group">
                                    <input name="customer_msisdn" type="text" class="form-control" id="loginTrials" placeholder="By Customer MSISDN (optional)" >
                                </div>-->

                                <!--<div class="form-group">
                                    <label>Send To:</label>
                                    <input name="email_send_to" type="text" class="form-control" id="loginTrials" placeholder="recepient emails comma separated (optional)" >
                                    <p class="help-block"><strong>Note:</strong> A copy of this report will be sent to your email address.</p>
                                </div>
                                <div class="form-group">
                                    <label>Message:</label>
                                    <textarea name="email_message" class="form-control" id="loginTrials" placeholder="Please find attached a copy of report from EKYC." ></textarea>
                                </div>-->


                                <div class="hr-line-dashed"></div>
                                <div class="row form-group">
                                    <div class="col-sm-8 col-sm-offset-2">
                                        <a class="btn btn-white">Cancel</a>
                                        <button class="btn btn-primary" type="submit">Generate Report</button>
                                    </div>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="referenceInfo" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Reference</h4>
                    </div>
                    <div class="modal-body">
                        <p>Some text in the modal.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>


        <script src="{{ asset('assets/js/core/agents.js') }}"></script>
        <script>
            $(document).ready(function () {
                getRegionsCode();
            });
        </script>

    {% endblock %}

src/aimgroup/DashboardBundle/Resources/views/Admin/side_navigation_bar.html.twig
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">

        <ul class="nav" id="side-menu">
            <li>
                <div class="dropdown profile-element">
                            <span>
                                <a href="{{ path('admin') }}">
                                    <img alt="Simreg 2.0" style="width: 100%;" class="img-circle"
                                         src="{{ asset('assets/img/logo.png') }}"/>
                                </a>
                            </span>
                </div>
                <div class="logo-element">
                    <a href="{{ path('admin') }}">
                        <img alt="Simreg 2.0" style="width: 55%; opacity: 0.85; "
                             src="{{ asset('assets/img/logo-small.png') }}"/>
                    </a>
                </div>
            </li>
            <li>
                <a href="{{ path('admin') }}"><i class="fa fa-home"></i> <span class="nav-label">Home</span></a>
            </li>
            <li>
                <a href="index.html"><i class="fa fa-table"></i> <span class="nav-label">Registrations</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{{ path('admin/registration') }}">View Registrations</a></li>
                    <li><a href="{{ path('admin/registration') }}?path=pending">Pending Registrations</a></li>
                    <li><a href="{{ path('admin/registration') }}?path=tobesent">Pending To be Sent</a></li>
                    <li><a href="{{ path('admin/registration') }}?path=treg">Treg</a></li>
                    <li><a href="{{ path('admin/registration') }}?path=freg">Freg</a></li>
                    <li><a href="{{ path('admin/registration') }}?path=declined">Declined</a></li>
                </ul>
            </li>
            <li>
                <a href="index.html"><i class="fa fa-certificate"></i> <span class="nav-label">Audit & Verification</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <!--<li><a href="{{ path('admin/registration') }}verify_registrations">Verify Registrations</a></li>
                    --><li><a href="{{ path('admin/registration') }}registrationaudit">Audit Registrations </a></li>
                    <li><a href="{{ path('admin/registration') }}multipleregistration">Multiple Registration</a></li>
                    <li><a href="{{ path('admin') }}audit_reports">Audit Reports</a></li>
                    <li><a href="{{ path('admin') }}verification_reports">Verification Reports</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-map-marker"></i> <span class="nav-label">Location Information</span> <span
                            class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{{ path('admin/region') }}display_map">Registrations</a></li>
                    <li><a href="{{ path('admin/region') }}display_map_agents">Agents</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ path('admin/agents') }}"><i class="fa fa-users"></i> <span
                            class="nav-label">Manage Agents</span> </a>
            </li>
            <li>
                <a href="{{ path('admin') }}reports"><i class="fa fa-area-chart"></i> <span class="nav-label">Report Generation</span></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-area-chart"></i> <span class="nav-label">Reports</span> <span
                            class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{{ path('admin') }}active_inactive">Active Inactive</a></li>
                    <li><a href="{{ path('admin') }}reg_journey">Registration Journey</a></li>
                    <li><a href="{{ path('admin') }}audit_reports">Audit Reports</a></li>
                    <!--<li><a href="{{ path('admin') }}verification_reports">Verification Reports</a></li>
                    --><li><a href="{{ path('admin') }}thirdparty_verifications">Third Party Verifications</a></li>
                </ul>
            </li>
            <!-- include administrator -->
            
            {{ isAdministrator ? include('includes/side_navigation_bar_admin.html.twig') : '' }}
            
            <!-- END -->
            <li>
                <a href="#"><i class="fa fa-user"></i> <span class="nav-label">Manage System Users</span> <span
                            class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{{ path('admin/users') }}sys_admin/23">Systems Admins</a></li>
                    <li><a href="{{ path('admin/users') }}admin_users/ROLE_SUPERAGENT">Super Agents</a></li>
                    <li><a href="{{ path('admin/users') }}vodashop">Vodacom Shops</a></li>
                </ul>
            </li>
            {{ isAdministrator ? include('includes/side_navigation_bar_diagnosis.html.twig') : '' }}
            <li>
                <a href="{{ path('faq') }}"><i class="fa fa-square-o"></i> <span class="nav-label">FAQs + Assists</span></a>
            </li>
        </ul>
    </div>
</nav>